### ISSUE TITLE
Add a if check for determining the REQUEST_CODE

### ISSUE THREAD

**Issue by JobGetabu** [syntaxltd/DroidLocation#4]
```
   @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        //droidLocationDelegate.showLocationSettingDialog(requestCode);
        droidLocationDelegate.doWeStartLocationService(resultCode);
    }
```

**Comment by JobGetabu** [comment]
This will assist child classes in overriding bugs 
for now comment out 
`//super.onActivityResult(requestCode, resultCode, data);`

in child classes

**Comment by JobGetabu** [comment]
Reproducing this Stacktrace.

```
Caused by: java.lang.NullPointerException: Attempt to read from field 'long ax.synt.droidlocation.DroidLocationRequest.fallBackToLastLocationTime' on a null object reference
        at ax.synt.droidlocation.DroidLocationDelegate.doWeStartLocationService(DroidLocationDelegate.java:189)
        at ax.synt.droidlocation.DroidLocationAppCompatActivity.onActivityResult(DroidLocationAppCompatActivity.java:38)
        at xx.LocationActivity.onActivityResult(LocationActivity.kt:91)
        at android.app.Activity.dispatchActivityResult(Activity.java:7695)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4700)
```
